### PR TITLE
Rework ui backend

### PR DESCRIPTION
**Pull request by Ennosigaeon**
This branch contains preparations for further ui-backend adjustment. Mainly, the code was formated, so no real changes. However, all REST endpoints were also changed to return Responses instead of POJO (fix of #78). Please merge this pull request after merging the angular4 branch.

### CODE REVIEW

**Comment by MichaelRoeder** [comment]
It looks like you haven't used the [`.editorconfig`](https://github.com/hobbit-project/platform/blob/master/.editorconfig) that is part of the platform project. Thus, the reformatting might simply be overwritten as soon as one of the other platform developers uses it. Can you please apply the formatting, that we already have defined for this project?

**Comment by Ennosigaeon** [comment]
I have removed linebreaks before `else` and `catch` and added spaces around array initialisations. This should be now complient with your code styles. Otherwise, I am not sure where my formatting violates the given code style.

**Comment by Ennosigaeon** [comment]
I have merged the current master into this branch. Can you (@MichaelRoeder) please merge this branch as I need these changes to continue with some of the other issues.

Basically, I have only changed all REST endpoints to return Responses instead of POJOs.

**Comment by MichaelRoeder** [comment]
Yes, but I would suggest to merge it into the develop branch after merging #134 since we try to follow http://nvie.com/posts/a-successful-git-branching-model/

I am wondering why you removed the public visibility from some methods (e.g., https://github.com/hobbit-project/platform/pull/130/files#diff-5710df18a3b3ebde3e26602dcc8bd693R90) and leave them without any modifiers. Especially since some of them are static methods.
And why you don't like the ArrayLists? :smile:

**Comment by MichaelRoeder** [comment]
I had to change the base of this pull request since merging the changes into `angular4` is not necessary but we need these changes in the `develop` branch.

**Comment by Ennosigaeon** [comment]
Sorry, I was busy the last days and forgot about this issue. My merge contains all changes, except the visualisation of the leaderboard. I wasn't initially sure how exactly the leaderboard is displayed and had no time to figure it out yet. You can either give me a few more days and I will add these changes as well or you can go ahead and modify the [leaderboard](https://github.com/hobbit-project/platform/tree/develop/hobbit-gui/gui-client/src/app/challenges/leaderboard) on your own.

**Comment by MichaelRoeder** [comment]
That is no problem at all. However, it would have been better to write a comment that the problem is/might be caused by the leaderboard. That would have been the information that we need to solve the problem either now or later.

You should never merge a branch with such a problem into another one. That was why I was "requesting Changes" with my review above :wink: 
Now, we __have to__ fix the problem on our own because the develop branch is not compiling anymore with the error reported above :disappointed: 

However, we will try to handle that. Please keep it in mind for the next time :wink:

**Comment by Ennosigaeon** [comment]
Sorry, about that. Currently, the develop branch is still working fine, the leaderboard is simple empty. But you are right, about the rest. Sorry... :cry:

**Comment by Ennosigaeon** [comment]
What the... Seems like I have totally messed up this merge... Ok, my suggestion to solve this mess: I will rollback my merge and restart from the beginning. This will potentially break the develop branch for you, so you would have to checkout it again. Does anybody have a better idea?

**Comment by MichaelRoeder** [comment]
I agree. Please do it that way. Thanks.

**Comment by MichaelRoeder** [comment]
Hint: you don't have to take care of commit https://github.com/hobbit-project/platform/commit/9ca34b5b60b49cf8113c865b41021b3295058571 that I made after the merge. You can simply remove it as well.

**Comment by denkv** [comment]
I resolved merge conflicts in `gui-client` stuff in temporary branch. After @MichaelRoeder resolves his part of merge conflict you'll be able to just merge it back to your branch.

**Comment by Ennosigaeon** [comment]
I have also prepared a new temp branch containing a conflict-free version of the dev branch. How will we proceed?

**Pull request merged**
