### PR TITLE
Angular4

### PR DESCRIPTION
**Pull request by Ennosigaeon**
This branch contains a general rework of the frontend by moving Angular2 to Angular4. Furthermore, the following frontend related issues were fixed:

- #35
- #66 
- #75 
- #79 
- #104

### CODE REVIEW

**Comment by Ennosigaeon** [comment]
Actually no. The JS request the keycloak config from the gui backend. Thats the request you have observed. This config contains the link to the actual keycloak server. Backend wasn't changed and should work as before. However, I currently have no idea why the start up fails for you.

**Comment by MichaelRoeder** [comment]
These are the addresses that are called from my browser:
```
http://192.168.99.100:8080/
http://192.168.99.100:8080/inline.bundle.js
http://192.168.99.100:8080/polyfills.bundle.js
http://192.168.99.100:8080/scripts.bundle.js
http://192.168.99.100:8080/styles.bundle.js
http://192.168.99.100:8080/vendor.bundle.js
http://192.168.99.100:8080/main.bundle.js
http://localhost:8181/rest/internal/keycloak-config
```
The first request is the initial request. The following requests are loading the JS files and the last one is the failing request. However, I can not see a call to the gui backend (at least not from my browser) that could cause the `localhost:8181` to be retrieved :confused:

**Comment by MichaelRoeder** [comment]
Is it possible that the behavior is caused by this line: https://github.com/hobbit-project/platform/blob/0e19883cd64adddac24d55f9e1572acfca1f0c7e/hobbit-gui/gui-client/src/environments/environment.ts#L8 ?

**Comment by Ennosigaeon** [comment]
Yes, you are right. I forgot to provide production environment variables. You can either change [environments.ts](https://github.com/hobbit-project/platform/blob/0e19883cd64adddac24d55f9e1572acfca1f0c7e/hobbit-gui/gui-client/src/environments/environment.ts) or the [prod environments](https://github.com/hobbit-project/platform/blob/0e19883cd64adddac24d55f9e1572acfca1f0c7e/hobbit-gui/gui-client/src/environments/environment.prod.ts) and compile the frontend using `ng build --prod --env=prod`

**Comment by MichaelRoeder** [comment]
Your fix seems to be a workaround but not a fix to the problem. Everybody with a different configuration would have to recompile the front end.

I think that the JS code will have to get the keycloak address from the GUI backend because the backend knows the address from its environment.
Could you please check how it has been implemented in the "old" version and update your branch accordingly?

**Comment by Ennosigaeon** [comment]
I have pushed two new commits that should fix the problems. Basically, I used port 8181 during development, but the "production" backend is running on 8080. Additionally, I have added [environments.prod.ts](https://github.com/hobbit-project/platform/blob/angular4/hobbit-gui/gui-client/src/environments/environment.prod.ts) that should be used for production builds.

Please compile the frontend using `ng b --prod`.

Just for clarification: The frontend is querying the Keycloak config from the backend. However, the backend url was configured incorrectly. Keycloak is just the first interaction with the backend.

**Comment by MichaelRoeder** [comment]
I was able to start it. A first, brief look showed, that the new GUI looks good :smiley: 

My storage is empty so the Warning is correct.
hobbit gui

However, it does not disappear when I go to another page.
hobbit gui 1

I will take a closer look during the next week.

**Comment by Ennosigaeon** [comment]
I have fixed the issue, that error messages are not cleared when changing the page.

**Comment by MichaelRoeder** [comment]
The former issues have been fixed. A further analysis showed the following problems. I couldn't go through all parts of the UI until now (since some buttons are missing, see below). So there might be further issues coming after fixing the following.

### Not all users should see the "Add challenge" button
At the moment, all users can see the "Add challenge" button. 
addchallengebutton

When a non challenge organizer clicks on the button, the screen to create a challenge is shown but all fields are not editable.
wrongaddchallenge

It would be better if the visibility of the "Add challenge" button would be restricted to users with the role `challenge-organiser`.

### Challenge organizer can not see registered systems
Comparing the new with the old UI, it can be seen that the button "Show registered systems" is missing in the view that shows the details of a challenge.
old UI:
oldui

new UI:
newui

The new button `System Registration` allows the user to register a system. Additionally, a user with the `challenge-organiser` role should be able to see the "Show registered systems" button to access a view on which he can see the systems that are registered for his/her challenge.

### Naming of buttons
From my point of view, the naming of the button `System Registration` is a little bit misleading - especially for challenge organisers. The two buttons in the old UI had more expressive names.

### Challenge registration button missing for non organisers
Users that don't have the `challenge-organiser` role can not see the button to register a system. This button should be visible for registered users (not for guests).
missingbutton

### Sorting in drop down box should be adapted (minor)
The sorting in the drop down box does not take the writing into account, i.e., whether a string starts with uppercase or lowercase.
dropdownsorting

From my point of view, it shouldn't matter whether something is written upper- or lower-cased.

### White bar on top (very minor)
There is a white bar on top of the top bar (checked in Chrome and Firefox). 
whitebar
Note that this is only a very minor detail.

**Comment by Ennosigaeon** [comment]
I have resolved all of your 5 issues.

**Comment by Ennosigaeon** [comment]
I am not sure what exactly you mean with "User does not see his system registrations". Assume I have registered some systems previously for a certain task/challenge and I open the system registrations page again, I see the following

screenshot

Both systems I had previously registered are already checked.

**Comment by MichaelRoeder** [comment]
That would be the perfect behavior :smile:
Unfortunately, I didn't saw that during my tests. I will check it again :confused:

**Comment by Ennosigaeon** [comment]
Regarding "Challenge task results cause crash": I had a look at the MOCHA TEST challenge. If I select any task experiments I get a result as expected

screenshot1

However, when I open the experiments of the DEBS Grand Challenge, I see the error as you have described. But I think this is caused by the GUI backend.  The query

`query?challenge-task-id=http://w3id.org/hobbit/challenges%23e5744a79-11fa-4f31-87a0-96411fdb5007_task1`

returns `null` as the [ExperimentResources](https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/ExperimentsResources.java) method _query_ finds no challenge task for the presented id. Yet, I am not sure why this challenge task isn't found.

**Comment by Ennosigaeon** [comment]
And finally, you were right with "System registration gambling". If have added a commit to fix a race-condition loading system registrations.

**Comment by MichaelRoeder** [comment]
You are right, it is bound to certain challenges, i.e., challenges that have no "public" results. Let me briefly summarize the workflow of the GUI backend (implement in this part https://github.com/hobbit-project/platform/blob/angular4/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/ExperimentsResources.java#L136-L174):

1. The GUI retrieves all experiment results that are publicly visible. If there are results, they are returned and the GUI works (as for DEBS).
2. If there are no public results, the GUI retrieves "private" results. In my local example, there are two results but I don't know whether MOCHA had private results - the actually should have public results :thinking: 
3. When there are results, the current user is compared with the organizer (which does not work because the fix for #122 is missing in this branch).
4. It checks whether the asking user is the owner of one of the systems and would return only these experiment results.
5. If there are still no results, an empty list will be returned.

I think you will have to take care of cases, in which the response can be empty. Although I like the error page that you show very much, it does not fit to this case and it would be better if the user gets a message that better fits this situation, e.g., if the number of experiments in the table (for the selected task) > 0 --> "The experiments are not publicly visible at the moment.". If the number is 0 --> "There are no experiments to show" (or something similar).
What do you think? Maybe it would be easier to adapt the backend to return something else than HTTP 204 in these cases?

**Comment by Ennosigaeon** [comment]
I totally agree with you. However, the result is `null` and not an empty list as line 143 evaluates to false, line 156 is false, the variable `result` is never assigned. This `null` response is not correctly parsed in the frontend, as a list is expected. I would suggest to replace line 83 with ` List<ExperimentBean> results = new ArrayList<>();` to guarantee that a list is returned.

**Comment by MichaelRoeder** [comment]
You are right. Fixed that.

Regarding the  "User does not see his system registrations" problem: I think that in your example, the user who registers the systems is also the user who owns the challenge. Is that right? In this case, the registration information is available for the UI client. However, when another user account asks for registered systems, he does not see any registrations and the UI client shows a list without any systems registered.

So I assume that this behavior has to be adapted in the backend at https://github.com/hobbit-project/platform/blob/angular4/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/SystemProviderResources.java#L97-L98
Does I understand it correct, that in this case the GUI-client should show the correct registrations?

**Comment by Ennosigaeon** [comment]
So far I have tested everything only with a single user, so you are right. I had thought that ?_getAllChallengeRegistrations_ returns all registered systems independent of the owner of the challenge and systems. So that is probably the cause for the misbehaviour. But I can check how this was previously solved as this has worked with the old UI, hasn't it?

**Comment by MichaelRoeder** [comment]
No, it hasn't worked in the old UI. That was why I was wondering how it is working now :smile: 

In the old UI, all checkboxes were always checked when you opened the screen. So you manually had to remove systems if you don't want them to take part in one of the challenge tasks.

If we can not show the current registration (for which we have to extend the backend. Its not a real problem but I would add it as an enhancement issue) we should have the old behaviour, i.e., simply check all boxes :wink:

**Comment by MichaelRoeder** [comment]
Sry, I forgot to mention one last issue of the new GUI. When submitting an experiment configuration, the screen shows the information about the experiment (very good) and also prints out the ID of the experiment. 
hobbit gui 5
In the old GUI, the ID was linked to the experiment result page of this experiment. But it had the disadvantage that for an "non-experienced users" it was not visible that the ID is working as link. In the new GUI, the ID is no link, anymore and the screen is like a dead end. I think it would be nice to have a link to the result page but with an explanation, e.g., "The result of the experiment will be available at LINK" or something similar.

**Comment by Ennosigaeon** [comment]
I don't think it is a good idea to simply check all systems if no registrations are found because challenge owner and current user (see [here](https://github.com/hobbit-project/platform/blob/angular4/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/SystemProviderResources.java#L97-L98)) are different. It would be better to replace to throw an exception as there is a semantic difference between there are no registrations and it is not possible to query the information about registrations. So my suggestion is to replace lines 97 and 98 to throw an exception and I add logic in the frontend to correctly process the information, e.g. checking all systems and displaying a message that it isn't possible to query current registrations.

**Comment by Ennosigaeon** [comment]
I have created the link to the experiment result as suggested.

**Comment by MichaelRoeder** [comment]
I thought, that if the user is not the challenge owner, we can simply check, which of his systems are registered. I just implemented it in the [`feature/user-reg-list`](https://github.com/hobbit-project/platform/tree/feature/user-reg-list) branch. From this line on, the check is done and the registration beans are filtered:
https://github.com/hobbit-project/platform/commit/fa5280d108dd24e6a813f21960d7d6caac0532aa#diff-e464ff1ed9d27b00875a8b4d6ad2b817R98
Please check whether this works for you as well. After that, you can simple merge it into the `angular4` branch.

There still seems to be a problem when registering systems... the gui-backend seems to offer the registration of systems that do not fit to the benchmark of the challenge task. I will double check that...

I discovered another tiny problem: when opening the challenge as a different user than the organizer, I still have the buttons `save`, `cancel` and `delete`. A simple `back` would fit much better, right?
hobbit gui 6

I think after fixing these, we should be ready to merge :smiley:

**Comment by Ennosigaeon** [comment]
Merging [feature/user-reg-list](/hobbit-project/platform/tree/feature/user-reg-list) actually solved the first issue. Additionally, I changed the buttons as you have suggested in 3.

**Comment by MichaelRoeder** [comment]
Problem 2 seems to be unrelated to the changes in angular. I created an issue for that (#133).

**Comment by Ennosigaeon** [comment]
Just as a summary, these are the tickets resolved in this pull request:

- #35
- #66
- #75
- #79
- #104
- #118

**Pull request merged**
