### PR TITLE
New VOS Docker Images for the Platform Storage

### PR DESCRIPTION
**Pull request by mjovanovik**
The VOS Docker images at [DockerHub](https://hub.docker.com/r/openlink/virtuoso_opensource/), which the HOBBIT Platform uses directly, were updated to the latest stable versions of Virtuoso Open-Source: VOS version 07.20.3217, from the [`stable/7` branch](https://github.com/openlink/virtuoso-opensource/tree/stable/7).

The VOS Docker images now use a different file system layout, which required several changes in Docker Compose and in the `virtuoso.ini` config file.

Additionally, since the source for creating the VOS Docker images is part of the Platform code, the file system path changes were updated as well, along with the corresponding README.

Initial tests showed that the HOBBIT Platform works properly. However, I'd suggest to @MichaelRoeder to also do a quick test before merging.

### CODE REVIEW

**Comment by MichaelRoeder** [comment]
There is a problem with the update. When I test it locally, the virtuoso is empty, i.e., I loose all the experiment results that I had before.

Is the newer virtuoso version backwards compatible? Shouldn't it be possible to give the "old" database to the new Virtuoso and it will update the old database and keep the data?

**Comment by mjovanovik** [comment]
@MichaelRoeder The transaction log is a file called `virtuoso.trx` which is in the same directory as the database `virtuoso.db`. But this information cannot help you, as the transaction logs are not compatible between these two VOS versions (in contrast, the databases are compatible).

So, in order to migrate your database from the previous VOS instance to the new VOS instance, you need to start the previous VOS instance and execute the following commands:

1. `checkpoint;`
2. `shutdown;`

The first command will force all database action stored in the transaction log file to get executed, and the second one will shut down the VOS instance. With this, you will no longer have a `virtuoso.trx` file, but simply the `virtuoso.db` database file, with all transactions executed. This will then allow a seamless transition to the new VOS instance, by simply reusing the `virtuoso.db` database. (Note: You can reuse `virtuoso.db` as it is, even without this. The problem you're facing is that cached actions, stored in `virtuoso.trx`, will not be persisted in the new VOS instance).

You can execute the two commands by logging in via the VOS GUI (conductor) and clicking on Interactive SQL (ISQL). From the popup window you can execute both these commands. An alternative approach would be to use the command-line tool `isql` which is available in the VOS directory under `bin/`.

**Comment by MichaelRoeder** [comment]
@mjovanovik did I understood you correctly, that the transaction file does not contain any data and that I could remove it as well? Wouldn't this be much easier for other users than the "correct way" you described before?

**Comment by mjovanovik** [comment]
@MichaelRoeder If a `virtuoso.trx` file exists, not everything is in the database. If you remove `virtuoso.trx`, you'll lose the transactions which are still in it. So, you need `checkpoint; shutdown;` to force a flush to the database.

**Comment by MichaelRoeder** [comment]
Ok, got that. The chechpoint is required before updating. 

The problem is that in praktice the current way is not working. Let's go through the steps that a "normal" user would do when updating his platform:
1. `docker-compose pull` to pull the latest changes
1. `docker-compose up`
1. realise, that the VOS is stopping with an error message
1. start `openlink/virtuoso_opensource:vos` and try to run the `checkpoint` command but the container is stopping again with the same error as before
What happened is that `docker-compose pull` checked for a newer version of `openlink/virtuoso_opensource:vos` and downloaded it. The old version is still on the PC but it has lost its version tag `vos` since a newer version with that tag has been downloaded. Now, it is very hard for the user to get the correct image running to run the `checkpoint` command.

If you want to fix this problem, you should use more helpful version tags, e.g., `vos_07.20.3217` and `vos_07.20.3217`. Btw., this does not mean that you still can have a `vos` image on dockerhub. You should simply supply several images with versions like it is done by [RabbitMQ](https://hub.docker.com/_/rabbitmq/) where you have `3.6.10`, `3.6`, `3`, `latest`.

Another question would be, whether it is easy to get the Virtuoso version that was used to create a `virtuoso.trx` out of that file. Based on that, we could write a script that handles the execution of the `checkpoint` and `shutdown` commands automatically (assuming that we can use a VOS image that has the version in its tag).

**Comment by mirkospasic** [comment]
There is a simpler solution. We have to be sure that "normal" user will shutdown the VOS correctly, before updating the platform. Right now, the platform just stops the VOS container, without making the checkpoint, or without execution of shutdown command (that will make the checkpoint as well). So, the previous image (with the old VOS instance) should have a feature which will execute shutdown command before stopping the container. I guess that something like that is possible, and this solution would be the easiest one.

**Comment by mjovanovik** [comment]
Yes, @mirkospasic is correct. The Platform should use Virtuoso **correctly**, i.e. shut it down when the Platform stops. As @mirkospasic says, issuing a single `shutdown` command to Virtuoso will make a checkpoint and shutdown correctly, so that all transactions are in the `virtuoso.db` database file.

**Comment by MichaelRoeder** [comment]
Shutting down the Virtuoso correctly is part of the Virtuoso image. It is nearly not possible to do that from outside the container in a clear and easy way.

When Docker asks the container to stop, a SIGTERM signal is send to the command running in the container. The Virtuoso could react with a `shutdown` command to itself.

**Comment by mjovanovik** [comment]
@MichaelRoeder It can easily be done from the Platform, using a single command like those in [this script](https://github.com/hobbit-project/platform/blob/master/config/db/storage-init.sh), if the new `dba` password is accessible to the script.

I'll investigate the possibility to shutdown VOS properly from inside the Docker image, using the SIGTERM signal you mentioned.

We'll also start using version tags on DockerHub for the VOS images from now on, but for now all we have there is the latest `stable/7` VOS version tagged as `vos`.

**Comment by MichaelRoeder** [comment]
I understood your suggestion that the platform should shutdown Virtuoso. However, I see several problems:
1. *Possibility 1: Platform-controller sends shutdown command.* When the platform is stopped, it is typically done using a command like `docker-compose down` which stops and removes all containers defined in a given docker-compose file including the virtuoso container. I am not sure whether docker-compose follows a certain order when shutting down the containers but it is possible that Virtuoso is already stopped when the platform controller sends the shutdown command. Apart from that problem, I am not even sure whether it is possible to let the platform-controller access an isql program that is inside another container.
1. *Possibility 2: Shutdown script.* It would be possible to write a shutdown script that stops all other containers, sends the shutdown signal to virtuoso and stops virtuoso afterwards. But that would decrease the usability of the platform (from my point of view) although it might be the easiest workaround.

Btw. I still have the older image on my PC, if you want to deploy it. I think that would be good as long as the problem described above exists. Otherwise, some of the partners will loose their data because they wouldn't be able to access the older version after they figured out that they need it to execute the `checkpoint` command.

Please let me know whether it is possible to shutdown the virtuoso from "inside" its container. This would make a lot of things easier and the Virtuoso image even more useful since it would follow a real component strategy where the single components are exchangable and thus have to make sure that they are started / stopped correctly.

**Comment by MichaelRoeder** [comment]
Is it possible that using the new version (which was stopping because of the existing transaction file) somehow set back the users? For some reason, the platform can not use the vos anymore using the `HobbitPlatform` user and when I connect to Virtuosos web interface, I can log in with `dba` and `dba` - which should not be possible anymore.

**Comment by mjovanovik** [comment]
The [new commit](https://github.com/hobbit-project/platform/pull/80/commits/cb9e3936c3f09208c09c413fb550b565d351d84e) contains precise version tags to be used for the VOS Docker images within the HOBBIT Platform. This should ensure a stable environment for the Platform to be able to use current and future VOS versions for the storage layer.

**Comment by MichaelRoeder** [comment]
The next platform version will use the `vos-hobbit` version of the virtuoso. After that, we should be ready to switch to the new virtuoso version.

Could you please add the Dockerfile of the `vos-hobbit` to the https://github.com/hobbit-project/platform/tree/master/platform-storage directory (or update the dockerfile in https://github.com/hobbit-project/platform/tree/master/platform-storage/virtuoso-docker accordingly)? That would ease the creation of the wrapper of the latest vos docker :wink:

**Comment by mjovanovik** [comment]
I added the new Dockerfile for creating `vos-hobbit` (Btw, `vos-hobbit` is also [available at Dockerhub](https://hub.docker.com/r/openlink/virtuoso_opensource/tags/)). 

Within this image, Virtuoso is not started directly by the Docker process, but by a wrapper script called `vos-interruptible.sh`, which is also included in the latest commit.

The `vos-interruptible.sh` script starts Virtuoso, and then waits for either Virtuoso to finish, or for a signal from the outside. If a `SIGTERM` signal arrives to the Docker container, it gets passed to the script, and then the scripts sends a different signal to Virtuoso - `SIGINT` - to allow Virtuoso to execute a normal shutdown (with a checkpoint), instead of the quick shutdown (without a checkpoint) which gets executed [if `SIGTERM` reaches Virtuoso](http://docs.openlinksw.com/virtuoso/signalsandexitcodess/). 

This translation mechanism which the scripts enforces, ensures that after the Docker containers of the Platform get stopped, all transactions from the Virtuoso transaction log (.trx) will get executed, and the database will be ready for migration.

**Comment by mjovanovik** [comment]
@MichaelRoeder All Virtuoso images (aside from `vos-hobbit`) **do not** use the `vos-interruptible` script.

The idea for `vos-interruptible` was to enable regular shutdown for Virtuoso, so that a migration to a newer Virtuoso instance was seamless. Previously, a migration was blocked by pending database transactions remaining in the `.trx` file, which was then incompatible with the transactions / database of the newer Virtuoso version. The question now is do we need `vos-interruptible`.

For straight-forward usage of all future Virtuoso releases, we'd need to skip the `vos-interruptible` mechanism and just use `openlink/virtuoso_opensource:v07.20.3217` or `openlink/virtuoso_opensource:latest`.

If we customize any of these images with `vos-interruptible`, the platform will depend on doing that for all future releases.

**Comment by MichaelRoeder** [comment]
I agree that being bound to the script is a clear drawback.

However, it might be possible that in the future it might be possible that a newer version of Virtuoso does not run correctly because the existing transactions have been generated by an older version (i.e., it might be possible to have the same situation again).
Shouldn't we try to avoid this situation by sticking to the script?

**Comment by mjovanovik** [comment]
To ensure usage of the latest and future Virtuoso Docker images, which are non-HOBBIT specific, we took another approach: we no longer need `vos-interruptible.sh` or the `vos-hobbit` image. Instead, we configure the interaction between docker-compose and Virtuoso.

The docker-compose configuration now specifies `SIGINT` as a default stop signal for the Virtuoso image, and also specifies a stop grace period of 2 minutes. The signal initiates a normal shutdown which will roll-forward all pending / cached database transactions (as opposed to a quick shutdown when the default `SIGTERM` is used). The grace period allows Virtuoso a specified maximum time to execute the normal shutdown, if the default 10 seconds are insufficient.

The Virtuoso Docker images were also updated: now Virtuoso is a top-level process within the images, so that it can catch the signal(s) sent by docker-compose. The latest VOS versions (`latest` and `v07.20.3217`) were also updated on [DockerHub](https://hub.docker.com/r/openlink/virtuoso_opensource/tags/) and can be used directly by the platform.

**Pull request merged**
